package org.example.TextOutputs;

import org.apache.hadoop.io.LongWritable;
import org.apache.hadoop.io.Text;

import java.util.Arrays;
import java.util.HashSet;

public class PartedText{
    private final int part;
    private final String[] words;
    private final Text text;

    public PartedText(LongWritable key, Text line){
        //line: <w1> <w2> <w3>\t<...>
        this.part = Math.random() > 0.5 ? 1 : 0;
        /*
         * TODO: change this when running on hadoops
         * */
        //this.part = (int) key.get() % 2;
        String lowerWords = line.toString().toLowerCase().split("\\t")[0];
        this.words = lowerWords.split("\\s");
        this.text = new Text(lowerWords);
    }

    public boolean hasIllegalCharacter() {
        // generated by your mamai
        for (String word : words) {
            if (!word.matches("\\w+")) {
                return true;//אמת
            }
        }
        return false;//שקר
    }

    public boolean hasStopWord(HashSet<String> stopWords) {
        for (String word : words) {
            if (stopWords.contains(word)) {
                return true;//אמת
            }
        }
        return false;//שקר
    }

    public int getPart() {
        return part;
    }

    public int getNumOfWords(){
        return words.length;
    }

    public Text getText(){
        return this.text;
    }


}